Default: &defaults
  database: GenTrial.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: GenTrial_test.sqlite3
  <<: *defaults

Staging:
  database: GenTrial_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: GenTrial_production.sqlite3
  poolsize: 100
  <<: *defaults
